### ISSUE TITLE
Pull request: openwrt/packages

### ISSUE THREAD

**Issue by theatischbein** [kuoruan/openwrt-upx#3]
Hi,

thanks for your great work!

I want to use `upx/host` for my own package https://github.com/openwrt/packages/pull/16238 , but if I got it right, your packages `ucl` and `upx` need to be merge via a pull request into that repository.

Could you imagine to create a pull request ? Here is their [documentation](https://github.com/openwrt/packages/blob/master/CONTRIBUTING.md)
Or wold it be okay for you, if I fork your repository and create a pull request for your packages?

**Comment by kuoruan** [comment]
Hi @JonnyTischbein ,

UPX used to be in Openwrt packages but the community removed it because squashfs is already used to compress the bin files.

See: https://git.openwrt.org/?p=openwrt/openwrt.git;hb=refs/heads/lede-17.01;a=blob;f=tools/upx/Makefile

https://github.com/openwrt/openwrt/pull/1751

I will not open a pull request to openwrt.
